### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by freiburgermsu** [wanglongqi/WriteTeX#27]
Hello,

I receive this error
```console
Latex error: check your latex file and preamble.
 CMD executed: xelatex "-output-directory=C:\Users\ANDREW~1\AppData\Local\Temp\writetex-bvhwybqn" -interaction=nonstopmode -halt-on-error "C:\Users\ANDREW~1\AppData\Local\Temp\writetex-bvhwybqn\writetex.tex" > "C:\Users\ANDREW~1\AppData\Local\Temp\writetex-bvhwybqn\writetex.out"
Traceback (most recent call last):
  File "writetex.py", line 377, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "writetex.py", line 175, in effect
    print(open(log_file).read(), file=sys.stderr)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANDREW~1\\AppData\\Local\\Temp\\writetex-bvhwybqn\\writetex.log'
```
when I execute WriteTex on Inkscape (Windows OS). How can the `log` file be created programmatically to resolve the error?

**Comment by freiburgermsu** [comment]
I receive this output
```console
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 20.6.29)
entering extended mode
! I can't find file `C:/Users/ANDREW'.
<to be read again> 
                   \protect 
<*> C:/Users/ANDREW~
                    1/AppData/Local/Temp/writetex-bvhwybqn/writetex.tex
Please type another input file name
! Emergency stop.
<to be read again> 
                   \protect 
<*> C:/Users/ANDREW~
                    1/AppData/Local/Temp/writetex-bvhwybqn/writetex.tex
No pages of output.
Transcript written on C:\Users\ANDREW~1\AppData\Local\Temp\writetex-bvhwybqn\te
xput.log.
```
when I create a `writetex.out` file in the appropriate folder and then `apply` the latex code.

**Comment by wanglongqi** [comment]
This seems to be a TeX-related issue.
