### ISSUE TITLE
Error Reading File

### ISSUE THREAD

**Issue by behollan** [wanglongqi/WriteTeX#5]
Hello,

First of all thank you for your work in continuing the legacy of TexText.

After installation, the extension starts fine. However, when I try to 'apply' or 'Live Preview' any of my TeX string, I have been receiving the following error:

Traceback (most recent call last):
```
Traceback (most recent call last):
  File "writetex.py", line 358, in <module>
    e.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "writetex.py", line 175, in effect
    self.merge_pdf2svg_svg(svg_file)
  File "writetex.py", line 293, in merge_pdf2svg_svg
    doc = inkex.etree.parse(svg_file)
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118635)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118982)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117894)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:112440)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106415)
IOError: Error reading file '$my user folder/\appdata\local\temp\writetex-yi3j67\writetex.svg': failed to load external entity "file:/$my user folder/appdata/local/temp/writetex-yi3j67/writetex.svg"
```

Currently running Inkscape 0.92.2, XeLatex, and both PDF2SVG and PStoEDIT.

Error seems to occur regardless of what is put in for the latex source. 

Also tried commenting out             
https://github.com/wanglongqi/WriteTeX/blob/b1f9deead9bb031625ede4d66a0f89bb10fb2194/writetex.py#L181-L192

Per a closed issue and had no luck there either. 

Let me know if you need any other information.

**Comment by wanglongqi** [comment]
Have you updated to the latest version?

If you commented out above lines, you should be able to locate the temp folder. What are the files in the folder?

**Comment by behollan** [comment]
Currently running v1.6.1

In that folder are:
- writetex.aux
- writetex.txt
- writetex.out
- writetex.pdf
- writetex.tex

Looking at the .pdf, .tex, and .txt files everything seems to be compiling properly and generating a pdf with the text I want on it.

**Comment by wanglongqi** [comment]
The `writetex.svg` file is missing. Seems something wrong with the PDFtoSVG convertor. What operating system you are using now? Is `pdf2svg` in path?

**Comment by behollan** [comment]
Currently running windows 10. pdf2svg doesn't show up in the path.

**Comment by wanglongqi** [comment]
Putting either `pdf2svg` or `pdftoedit` in the path, the extension should work properly.

**Comment by behollan** [comment]
That fixed it. Odd that it didn't get set during the PStoEdit or pdf2svg install. Thank you for all your help!

**Comment by pandeysudan27** [comment]
It did not work for me.
