### ISSUE TITLE
Error reading temp file

### ISSUE THREAD

**Issue by MolochBaal** [wanglongqi/WriteTeX#9]
When I try to use the extension, I get this error:

IOError: Error reading file 'c:\users\victor\appdata\local\temp\writetex-upcfhd\writetex.svg': failed to load external entity "file:/c:/users/victor/appdata/local/temp/writetex-upcfhd/writetex.svg"

I think I have everything installed properly. Any idea what is happening?

**Comment by wanglongqi** [comment]
Please provide your input and version of script you use.

**Comment by MolochBaal** [comment]
I'm using WriteTeX 1.6.2, Inkscape 0.92 r15371, and the input was
https://imgur.com/a/uBwXD
It gives the same error for xelatex too.
This is the complete error vindow:

> Traceback (most recent call last):
  File "writetex.py", line 347, in <module>
    e.affect()
  File "D:\Programas\Inkscape\share\extensions\inkex.py", line 283, in affect
    self.effect()
  File "writetex.py", line 164, in effect
    self.merge_pdf2svg_svg(svg_file)
  File "writetex.py", line 282, in merge_pdf2svg_svg
    doc = inkex.etree.parse(svg_file)
  File "src\lxml\lxml.etree.pyx", line 3427, in lxml.etree.parse (src\lxml\lxml.etree.c:78767)
  File "src\lxml\parser.pxi", line 1793, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:114608)
  File "src\lxml\parser.pxi", line 1819, in lxml.etree._parseDocumentFromURL (src\lxml\lxml.etree.c:114955)
  File "src\lxml\parser.pxi", line 1723, in lxml.etree._parseDocFromFile (src\lxml\lxml.etree.c:113867)
  File "src\lxml\parser.pxi", line 1126, in lxml.etree._BaseParser._parseDocFromFile (src\lxml\lxml.etree.c:108614)
  File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:102150)
  File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:103800)
  File "src\lxml\parser.pxi", line 622, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:102669)
IOError: Error reading file 'c:\users\victor\appdata\local\temp\writetex-znmejr\writetex.svg': failed to load external entity "file:/c:/users/victor/appdata/local/temp/writetex-znmejr/writetex.svg"

**Comment by wanglongqi** [comment]
Do you have pdf2svg in your path?

**Comment by MolochBaal** [comment]
I suppose not, but I can't seem to find the "unofficial pdf2svg binaries" for Windows that you mention on your website.

**Comment by wanglongqi** [comment]
`pdf2svg` releases their official binaries recently, you can download from their repository. The unofficial one can be download from [releases page](https://github.com/wanglongqi/WriteTeX/releases/download/v1.1/pdf2svg-x64.7z).

**Comment by MolochBaal** [comment]
Okay, I've installed the binaries, but now I can't even open Inkscape >_<
I get this error:
https://imgur.com/a/wPUOO
Which I guess it could be translated as "Can't find entry point of process g_network_monitor_get_network_metered in the dynamic-link library D:\Programas\Inkscape\libgiomm-2.4-1.dll"

**Comment by wanglongqi** [comment]
I think you need to reinstall inkscape. Put pdf2svg into search path, do not copy the files into inkscape folder. They are not compiled with the same version of dynamic libraries, and normally inkscape folder does not in the path variable.

**Comment by MolochBaal** [comment]
What do you mean by "search path"?

**Comment by wanglongqi** [comment]
Check this [webpage.](https://www.computerhope.com/issues/ch000549.htm)
